//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.04 at 01:49:18 PM EDT
//


package io.apiman.test.common.plan;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 *  <xs:complexType>
 *       <xs:sequence>
 *         <xs:element name="skipStorage" type="xs:string" minOccurs="0"/>
 *         <xs:element name="testGroup" type="tns:testGroupType" maxOccurs="unbounded"/>
 *       &lt;sequence>
 *       <xs:attribute name="name" type="xs:string" use="required"/>
 *       <xs:attribute name="endpoint" type="xs:string"/>
 *     &lt;complexType>
 *   &lt;element>
 *
 *   <xs:complexType name="testGroupType">
 *     <xs:sequence>
 *       <xs:element name="test" type="tns:testType" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
 *     &lt;sequence>
 *     <xs:attribute name="name" type="xs:string" use="required"/>
 *     <xs:attribute name="endpoint" type="xs:string"/>
 *   &lt;complexType>
 *
 *   <xs:complexType name="testType">
 *     <xs:simpleContent>
 *       <xs:extension base="xs:string">
 *         <xs:attribute name="name" type="xs:string" use="required"/>
 *         <xs:attribute name="endpoint" type="xs:string"/>
 *         <xs:attribute name="delay" type="xs:int"/>
 *       &lt;extension>
 *     &lt;simpleContent>
 *   &lt;complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "testGroup"
})
@XmlRootElement(name = "testPlan")
public class TestPlan {

    @XmlElement(required = true)
    protected List<TestGroupType> testGroup;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "endpoint")
    protected String endpoint;

    /**
     * Gets the value of the testGroup property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testGroup property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestGroup().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestGroupType }
     *
     *
     */
    public List<TestGroupType> getTestGroup() {
        if (testGroup == null) {
            testGroup = new ArrayList<>();
        }
        return this.testGroup;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the endpoint property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEndpoint() {
        return endpoint;
    }

    /**
     * Sets the value of the endpoint property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEndpoint(String value) {
        this.endpoint = value;
    }
}
